kind: pipeline
name: AtomX Drone

steps:
 - name: compile
   image: archlinux:base-devel
   environment:
     BOT_API_KEY:
       from_secret: BOT_API_KEY
     CHAT_ID:
       from_secret: CHAT_ID
     SOURCE:
       from_secret: SOURCE
   commands:
      - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
      - cd /drone/src
      - bash builder.sh
