clone:
  depth: 1
kind: pipeline
name: AtomX Drone

steps:
 - name: compile
   image: atomxorg/ubuntu:latest
   environment:
     BOT_API_KEY:
       from_secret: BOT_API_KEY
     CHAT_ID:
       from_secret: CHAT_ID
     SOURCE:
       from_secret: SOURCE
   commands:
      - cd /drone/src
      - /noclone3 bash Setup.sh

trigger:
  event:
  - custom