clone:
  depth: 1
kind: pipeline
name: AtomX Drone

steps:
 - name: compile
   image: atomxorg/arch-linux:kernel
   environment:
     BOT_API_KEY:
       from_secret: BOT_API_KEY
     CHAT_ID:
       from_secret: CHAT_ID
     GH_TOKEN:
       from_secret: GH_TOKEN
   commands:
      - cd /drone/src
      - bash Setup.sh
   debug: true

trigger:
  event:
  - custom
  - cron
