kind: pipeline
type: docker
name: AtomX Drone

steps:
 - name: compile
   image: alpine:latest
   environment:
     BOT_API_KEY:
       from_secret: BOT_API_KEY
     CHAT_ID:
       from_secret: CHAT_ID
     SOURCE:
       from_secret: SOURCE
   commands:
      - apk -i upgrade
      - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
      - apk add gcc llvm lld g++-multilib clang git libxml2 python3-pip gcc llvm lld g++-multilib clang git automake lzop bison gperf zip curl zlib1g-dev libxml2-utils bzip squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng bc libstdc++6 libncurses5 wget python3 python3-pip gcc clang libssl-dev rsync flex git-lfs libz3-dev libz3-4 axel tar bc binutils-dev bison build-essential ca-certificates ccache clang cmake curl file flex git lld make python3-dev texinfo u-boot-tools xz-utils
      - cd /drone/src
      - bash builder.sh
